import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { getAllPages } from "../utils/data";

interface HomeProps {
  pages: string[];
}

const Home: NextPage<HomeProps> = ({ pages }) => {
  const router = useRouter();

  const routerHandler = (pageName: string) => {
    const path = router.pathname.split("/");
    if (path.length > 0) {
      path.pop();
    }
    path.push("pages-wiki");
    path.push(`${pageName}.html`);
    return path.join("/");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Wikipedia Upload</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to a wikipedia backup in Swarm!
        </h1>

        <p className={styles.description}>Checkout all the pages!</p>

        <div className={styles.grid}>
          {pages.map((pageName) => {
            return (
              <div key={pageName} className={styles.card}>
                <Link href={routerHandler(pageName)} passHref>
                  <a>{pageName}</a>
                </Link>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export async function getStaticProps() {
  const pages = getAllPages();
  return {
    props: {
      pages,
    },
  };
}

export default Home;
